name: Release

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get tag
        id: gen-tag
        run: |
          version=$(cat server/version.json | jq -r .version)
          echo tag="v$version" >> $GITHUB_OUTPUT
      - name: Push tag to repo
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.gen-tag.outputs.tag}}',
              sha: context.sha
            })
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
      - uses: actions/checkout@v4
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
          workdir: ./server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
